#!/usr/bin/env bash
# Bash script that will display information about subdomains
# shellcheck disable=SC2086

query_dns() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record=$(dig +short $sub.$domain)
        if [ -n "$record" ]; then
            echo "The subdomain $sub is a $(dig +short -t CNAME $sub.$domain | awk '{print $1}') record and points to $record"
        fi
    done
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2
query_dns "$domain" "$subdomain"