#!/usr/bin/env bash
# Bash script to Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get update -y
apt-get install -y nginx

service nginx start

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo nginx -t
service nginx reload