#!/usr/bin/env bash
# Bash script to Configure your Nginx server to have a custom 404 page.

apt-get update -y
apt-get install -y nginx

service nginx start

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 404 \"Ceci n'est pas une page\";
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo nginx -t
service nginx reload
