#!/usr/bin/env bash
# This script Configure Nginx so that its HTTP response contains a custom header.
# shellcheck disable=SC2154

apt-get update -y
apt-get upgrade -y
apt-get install -y nginx

service nginx start
service nginx enable

HOSTNAME=$(hostname)

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        add_header X-Served-By $HOSTNAME;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo nginx -t
service nginx reload
