#!/usr/bin/env bash
# a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your process.
# shellcheck disable=SC2009

ps aux | grep bash | grep -v grep
