#!/usr/bin/env bash
# a Bash script kill a process then prints I am invincible when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' SIGTERM

while true;
do
  echo "To infinity and beyond"
  sleep 2
done;
