#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"
while IFS=: read -r username password userid groupid _ homedir cmdshell
do
        echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. USER ID's place is protected by the passcode $password, more info about the user here: $userid"

done < $file
